/**
 * P11-T2: Parser Crash Resilience Tests
 *
 * Validates that the scanner degrades gracefully when parsers encounter
 * malformed input. Three scenarios:
 *   A) Malformed PE — PE parser errors, byte-stream still catches marker
 *   B) ZIP bomb + EICAR — bomb entry skipped, EICAR in entry 2 detected
 *   C) Malformed PDF — xref parse fails, byte-stream catches marker
 *
 * Test samples are generated by tests/hardening/crafted_crash_pe.py
 * and stored in tests/hardening/testdata/.
 */

#define _CRT_SECURE_NO_WARNINGS
#include <gtest/gtest.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

#include "../../include/akesoav.h"
#include "../../src/database/sigdb.h"
#include "../../src/signatures/aho_corasick.h"
#include "../../src/signatures/hash_matcher.h"

/* ── Helpers ─────────────────────────────────────────────────────────── */

static void push_u32(std::vector<uint8_t>& v, uint32_t val) {
    v.push_back((uint8_t)(val & 0xFF));
    v.push_back((uint8_t)((val >> 8) & 0xFF));
    v.push_back((uint8_t)((val >> 16) & 0xFF));
    v.push_back((uint8_t)((val >> 24) & 0xFF));
}
static void push_i64(std::vector<uint8_t>& v, int64_t val) {
    for (int i = 0; i < 8; i++)
        v.push_back((uint8_t)((val >> (i * 8)) & 0xFF));
}
static void push_bytes(std::vector<uint8_t>& v, const void* data, size_t len) {
    v.insert(v.end(), (const uint8_t*)data, (const uint8_t*)data + len);
}
static void push_zeros(std::vector<uint8_t>& v, size_t count) {
    for (size_t i = 0; i < count; i++) v.push_back(0);
}

/* AC_MARKER — same 48-byte pattern as crafted_crash_pe.py */
static const uint8_t AC_MARKER[] = {
    0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF, 0x11, 0x22,
    0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0x00,
    'A','K','A','V','_','C','R','A','S','H','_',
    'R','E','S','I','L','I','E','N','C','E','_',
    'T','E','S','T','_','M','A','R','K','E','R'
};

/* EICAR test string */
static const char EICAR[] =
    "X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*";

static std::vector<uint8_t> read_file(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) return {};
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    std::vector<uint8_t> data((size_t)len);
    fread(data.data(), 1, (size_t)len, f);
    fclose(f);
    return data;
}

/* Build a test .akavdb with EICAR MD5 + bytestream for both EICAR and AC_MARKER */
static std::vector<uint8_t> build_test_db() {
    /* Compute EICAR MD5 */
    uint8_t eicar_md5[16];
    akav_hash_md5((const uint8_t*)EICAR, 68, eicar_md5);

    /* Build AC automaton with 2 patterns:
     *   Pattern 0: first 16 bytes of EICAR (byte-stream)
     *   Pattern 1: first 16 bytes of AC_MARKER */
    akav_ac_t* ac = akav_ac_create();
    akav_ac_add_pattern(ac, (const uint8_t*)EICAR, 16, 0);
    akav_ac_add_pattern(ac, AC_MARKER, 16, 1);
    akav_ac_finalize(ac);

    size_t ac_size = akav_ac_serialize(ac, nullptr, 0);
    std::vector<uint8_t> ac_buf(ac_size);
    akav_ac_serialize(ac, ac_buf.data(), ac_size);
    akav_ac_destroy(ac);

    /* String table */
    const char strtab[] = "EICAR-Test-File\0CrashResilience.Marker\0";
    size_t strtab_size = sizeof(strtab) - 1; /* include embedded nulls */
    uint32_t eicar_name_idx = 0;

    /* MD5 entry: hash(16) + name_index(4) = 20 bytes */
    std::vector<uint8_t> md5_section;
    push_bytes(md5_section, eicar_md5, 16);
    push_u32(md5_section, eicar_name_idx);

    /* Section layout: MD5, AC, StringTable */
    uint32_t header_size = 280; /* AKAV_DB_HEADER_SIZE */
    uint32_t section_count = 3;
    uint32_t section_table_size = section_count * 16;
    uint32_t data_start = header_size + section_table_size;

    uint32_t md5_offset = data_start;
    uint32_t md5_size = (uint32_t)md5_section.size();
    uint32_t ac_offset = md5_offset + md5_size;
    uint32_t ac_size_u32 = (uint32_t)ac_buf.size();
    uint32_t str_offset = ac_offset + ac_size_u32;
    uint32_t str_size = (uint32_t)strtab_size;

    /* Build the file */
    std::vector<uint8_t> db;

    /* Header (280 bytes) */
    push_u32(db, 0x56414B41);  /* magic "AKAV" */
    push_u32(db, 1);           /* version */
    push_u32(db, 3);           /* signature_count (1 MD5 + 2 AC patterns) */
    push_i64(db, (int64_t)time(nullptr));  /* created_at */
    push_u32(db, section_count);
    push_zeros(db, 256);       /* RSA signature (zeros = unsigned) */

    /* Section table */
    /* MD5 section */
    push_u32(db, 1);           /* AKAV_SECTION_MD5 */
    push_u32(db, md5_offset);
    push_u32(db, md5_size);
    push_u32(db, 1);           /* 1 MD5 entry */

    /* AC section */
    push_u32(db, 4);           /* AKAV_SECTION_AHO_CORASICK */
    push_u32(db, ac_offset);
    push_u32(db, ac_size_u32);
    push_u32(db, 2);           /* 2 AC patterns */

    /* String table */
    push_u32(db, 0xFF);        /* AKAV_SECTION_STRING_TABLE */
    push_u32(db, str_offset);
    push_u32(db, str_size);
    push_u32(db, 0);

    /* Section data */
    push_bytes(db, md5_section.data(), md5_section.size());
    push_bytes(db, ac_buf.data(), ac_buf.size());
    push_bytes(db, strtab, strtab_size);

    return db;
}

/* ── Test Fixture ────────────────────────────────────────────────────── */

class ParserResilience : public ::testing::Test {
protected:
    akav_engine_t* engine = nullptr;
    std::string testdata_dir;
    std::string db_path;

    void SetUp() override {
        /* Find testdata directory relative to executable */
        testdata_dir = "tests/hardening/testdata";

        /* Build and write test DB */
        auto db = build_test_db();
        db_path = testdata_dir + "/resilience_test.akavdb";
        FILE* f = fopen(db_path.c_str(), "wb");
        ASSERT_NE(f, nullptr) << "Cannot write test DB to " << db_path;
        fwrite(db.data(), 1, db.size(), f);
        fclose(f);

        /* Create and init engine */
        akav_error_t err = akav_engine_create(&engine);
        ASSERT_EQ(err, AKAV_OK);
        err = akav_engine_init(engine, nullptr);
        ASSERT_EQ(err, AKAV_OK);
        err = akav_engine_load_signatures(engine, db_path.c_str());
        ASSERT_EQ(err, AKAV_OK);
    }

    void TearDown() override {
        if (engine) {
            akav_engine_destroy(engine);
            engine = nullptr;
        }
    }
};

/* ── Scenario A: Malformed PE ────────────────────────────────────────── */

TEST_F(ParserResilience, MalformedPE_ByteStreamStillCatches) {
    auto data = read_file((testdata_dir + "/malformed_pe.exe").c_str());
    ASSERT_FALSE(data.empty()) << "Cannot read malformed_pe.exe - run crafted_crash_pe.py first";

    akav_scan_result_t result;
    akav_scan_options_t opts;
    akav_scan_options_default(&opts);
    opts.use_whitelist = 0;

    akav_error_t err = akav_scan_buffer(engine, data.data(), data.size(),
                                         "malformed_pe.exe", &opts, &result);

    /* No crash — that's the primary assertion */
    EXPECT_EQ(err, AKAV_OK) << "Scan should not crash on malformed PE";

    /* Byte-stream should catch the AC_MARKER pattern */
    EXPECT_EQ(result.found, 1) << "AC should detect marker in raw bytes";
    EXPECT_STREQ(result.scanner_id, "aho_corasick")
        << "Detection should come from byte-stream, not hash";
}

/* ── Scenario B: ZIP bomb + EICAR ────────────────────────────────────── */

TEST_F(ParserResilience, ZipBomb_EicarInEntry2StillDetected) {
    auto data = read_file((testdata_dir + "/bomb_eicar.zip").c_str());
    ASSERT_FALSE(data.empty()) << "Cannot read bomb_eicar.zip - run crafted_crash_pe.py first";

    akav_scan_result_t result;
    akav_scan_options_t opts;
    akav_scan_options_default(&opts);
    opts.scan_archives = 1;

    akav_error_t err = akav_scan_buffer(engine, data.data(), data.size(),
                                         "bomb_eicar.zip", &opts, &result);

    /* EICAR in entry 2 should be detected despite bomb in entry 1 */
    EXPECT_EQ(result.found, 1) << "EICAR in entry 2 should be detected";

    /* If found, err should be AKAV_OK (not AKAV_ERROR_BOMB) because
     * malware was detected — the bomb is secondary */
    if (result.found) {
        EXPECT_EQ(err, AKAV_OK)
            << "Should return AKAV_OK when malware detected despite bomb";
    }

    /* Bomb warning should be logged */
    EXPECT_GT(result.warning_count, 0)
        << "Bomb in entry 1 should generate a warning";
}

/* ── Scenario C: Malformed PDF ───────────────────────────────────────── */

TEST_F(ParserResilience, MalformedPDF_ByteStreamStillCatches) {
    auto data = read_file((testdata_dir + "/malformed_pdf.pdf").c_str());
    ASSERT_FALSE(data.empty()) << "Cannot read malformed_pdf.pdf - run crafted_crash_pe.py first";

    akav_scan_result_t result;
    akav_scan_options_t opts;
    akav_scan_options_default(&opts);

    akav_error_t err = akav_scan_buffer(engine, data.data(), data.size(),
                                         "malformed_pdf.pdf", &opts, &result);

    /* No crash */
    EXPECT_EQ(err, AKAV_OK) << "Scan should not crash on malformed PDF";

    /* Byte-stream should catch the AC_MARKER in the raw PDF bytes */
    EXPECT_EQ(result.found, 1) << "AC should detect marker in raw PDF bytes";
    if (result.found) {
        EXPECT_STREQ(result.scanner_id, "aho_corasick")
            << "Detection should come from byte-stream on raw file";
    }
}

/* ── Bonus: Verify no crash on zero-length and truncated inputs ──────── */

TEST_F(ParserResilience, EmptyInput_NoCrash) {
    akav_scan_result_t result;
    akav_scan_options_t opts;
    akav_scan_options_default(&opts);

    akav_error_t err = akav_scan_buffer(engine, nullptr, 0,
                                         "empty.bin", &opts, &result);
    EXPECT_EQ(err, AKAV_OK);
    EXPECT_EQ(result.found, 0);
}

TEST_F(ParserResilience, TruncatedPE_NoCrash) {
    /* Just an MZ header with nothing after it */
    uint8_t stub[] = { 'M', 'Z', 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0 };

    akav_scan_result_t result;
    akav_scan_options_t opts;
    akav_scan_options_default(&opts);

    akav_error_t err = akav_scan_buffer(engine, stub, sizeof(stub),
                                         "truncated.exe", &opts, &result);
    EXPECT_EQ(err, AKAV_OK);
    EXPECT_EQ(result.found, 0);
}
