# BuildYara.cmake -- Fetch and build libyara as a static library.
#
# Produces a target `yara_lib` that other targets can link against.
# Compiles YARA v4.5.2 core + proc/windows.c with a no-module stub
# (basic string/hex matching only — no pe/elf/math module conditions).

include(FetchContent)

FetchContent_Declare(
    yara
    GIT_REPOSITORY https://github.com/VirusTotal/yara.git
    GIT_TAG        v4.5.2
    GIT_SHALLOW    TRUE
    EXCLUDE_FROM_ALL
)
FetchContent_MakeAvailable(yara)

# ── Gather core libyara source files ──────────────────────────────
file(GLOB YARA_CORE_SRCS "${yara_SOURCE_DIR}/libyara/*.c")

# Remove any existing modules.c (it's generated by autotools, may not exist in git)
list(FILTER YARA_CORE_SRCS EXCLUDE REGEX "modules\\.c$")

# Windows process scanning
set(YARA_PROC_SRCS "${yara_SOURCE_DIR}/libyara/proc/windows.c")

# ── Generate stub modules.c (no module support) ──────────────────
# This provides the module dispatch functions that YARA's core expects.
# Rules using "import pe" etc. will fail compilation, but basic
# string/hex/condition matching works perfectly.
file(WRITE "${yara_BINARY_DIR}/modules_stub.c" [=[
/* Auto-generated stub — no YARA modules enabled */
#include <yara/modules.h>

int yr_modules_do_declarations(
    const char* module_name, YR_OBJECT* main_structure)
{
    (void)module_name;
    (void)main_structure;
    return ERROR_UNKNOWN_MODULE;
}

int yr_modules_do_load(
    const char* module_name, YR_SCAN_CONTEXT* context,
    YR_OBJECT* module_object, void* module_data, size_t module_data_size)
{
    (void)module_name;
    (void)context;
    (void)module_object;
    (void)module_data;
    (void)module_data_size;
    return ERROR_UNKNOWN_MODULE;
}

int yr_modules_do_unload(
    const char* module_name, YR_OBJECT* module_object)
{
    (void)module_name;
    (void)module_object;
    return ERROR_UNKNOWN_MODULE;
}

int yr_modules_initialize(void)
{
    return ERROR_SUCCESS;
}

int yr_modules_finalize(void)
{
    return ERROR_SUCCESS;
}

int yr_modules_load(const char* module_name, YR_SCAN_CONTEXT* context)
{
    (void)module_name;
    (void)context;
    return ERROR_UNKNOWN_MODULE;
}

int yr_modules_unload_all(YR_SCAN_CONTEXT* context)
{
    (void)context;
    return ERROR_SUCCESS;
}
]=])

# ── Generate config.h for Windows/MSVC ────────────────────────────
file(WRITE "${yara_BINARY_DIR}/config.h" [=[
/* Auto-generated config.h for YARA on Windows/MSVC */
#ifndef YARA_CONFIG_H
#define YARA_CONFIG_H

#define PACKAGE_VERSION "4.5.2"
#define PACKAGE_STRING "yara 4.5.2"

#define HAVE_STDBOOL_H 1
#define HAVE_STDINT_H 1

/* Use Windows threading */
#define USE_WINDOWS_PROC 1

/* No OpenSSL — use built-in crypto where possible */
/* #undef HAVE_LIBCRYPTO */

/* TLSH support (built-in) */
/* #undef HAVE_WINCRYPT_H */

#endif /* YARA_CONFIG_H */
]=])

# ── Build static library ─────────────────────────────────────────
add_library(yara_lib STATIC
    ${YARA_CORE_SRCS}
    ${YARA_PROC_SRCS}
    "${yara_BINARY_DIR}/modules_stub.c"
)

target_include_directories(yara_lib
    PUBLIC "${yara_SOURCE_DIR}/libyara/include"
    PRIVATE "${yara_SOURCE_DIR}/libyara"
    PRIVATE "${yara_BINARY_DIR}"  # for config.h
)

target_compile_definitions(yara_lib PRIVATE
    YR_BUILDING_LIBYARA
    USE_WINDOWS_PROC
    HAVE_STDBOOL_H=1
    HAVE_STDINT_H=1
    _CRT_SECURE_NO_WARNINGS
    BUCKETS_256
    # Disable features we don't need
    YR_BUILDING_MODULE_ONLY=0
)

# Link Windows threading and crypto
target_link_libraries(yara_lib PRIVATE crypt32.lib advapi32.lib)

# Suppress warnings on third-party code
if(MSVC)
    target_compile_options(yara_lib PRIVATE /W0)
elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    target_compile_options(yara_lib PRIVATE -w)
endif()
